---
    name: build-ublue-custom
    on:
      pull_request:
        branches:
          - main
      workflow_dispatch:
    jobs:
      call_reusable:
        uses: johannesbremer/joblue/.github/workflows/build-image.yml@main
        secrets:
          SIGNING_SECRET: inherit